name: build

on:
  push:
    tags:
      - "*"
env:
  CARGO: cargo

jobs:
  build:
    name: Release
    strategy:
      matrix:
        job:
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-musl }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
          - { os: macos-latest, target: x86_64-apple-darwin }
    runs-on: ${{ matrix.job.os }}
    timeout-minutes: 20
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          target: ${{ matrix.job.target }}

      - name: Install Cross
        shell: bash
        if: ${{ startsWith(matrix.job.target, 'aarch64') || endsWith(matrix.job.target, 'musl') }}
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV

      - name: Build
        shell: bash
        run: ${{ env.CARGO }} build --features=cli --target=${{ matrix.job.target }}

      - name: Test
        shell: bash
        run: ${{ env.CARGO }} test --features=vimdoc --target=${{ matrix.job.target }}
